FROM python:3.11.9-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR app

RUN pip install poetry

RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./

RUN poetry install

COPY scripts/entrypoint.sh ./entrypoint.sh
COPY bot .

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]