name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: repo checout
        uses: actions/checkout@v4

      - name: installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: installing poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: installing deps
        run: poetry install --no-interaction --no-root

      - name: run tests
        run: poetry run pytest --maxfail=5 --disable-warnings -v
